FROM mcr.microsoft.com/dotnet/sdk:6.0

RUN mkdir /src
WORKDIR /src
ADD . /src
RUN dotnet restore
RUN ["dotnet", "build", "--configuration", "release"]

EXPOSE 5011 5014

ENV ASPNETCORE_URLS="http://+:5011;https://+:5014"
ENV ASPNETCORE_ENVIRONMENT="Production"
RUN ["dotnet", "dev-certs", "https"]

ENTRYPOINT [ "dotnet", "run", "--no-launch-profile" ]