#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 5014 5015

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["OctopusSamples.OctoPetShop.ProductService/OctopusSamples.OctoPetShop.ProductService.csproj", "OctopusSamples.OctoPetShop.ProductService/"]
RUN dotnet restore "OctopusSamples.OctoPetShop.ProductService/OctopusSamples.OctoPetShop.ProductService.csproj"
COPY . .
WORKDIR "/src/OctopusSamples.OctoPetShop.ProductService"
RUN dotnet build "OctopusSamples.OctoPetShop.ProductService.csproj" -c Release -o /app/build

ENV ASPNETCORE_URLS="http://+:80;https://+:443"
ENV ASPNETCORE_ENVIRONMENT="Production"
RUN ["dotnet", "dev-certs", "https"]

FROM build AS publish
RUN dotnet publish "OctopusSamples.OctoPetShop.ProductService.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "OctopusSamples.OctoPetShop.ProductService.dll"]