FROM mcr.microsoft.com/dotnet/sdk:6.0

RUN mkdir /src
WORKDIR /src
ADD . /src
RUN dotnet restore
RUN ["dotnet", "build", "--configuration", "release"]

EXPOSE 5000 5001

ENV ASPNETCORE_URLS="http://+:5000;https://+:5001"
ENV ASPNETCORE_ENVIRONMENT="Production"
RUN ["dotnet", "dev-certs", "https"]

ENTRYPOINT [ "dotnet", "run", "--no-launch-profile" ]
