#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 5000 5001

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["OctopusSamples.OctoPetShop.Web/OctopusSamples.OctoPetShop.Web.csproj", "OctopusSamples.OctoPetShop.Web/"]
RUN dotnet restore "OctopusSamples.OctoPetShop.Web/OctopusSamples.OctoPetShop.Web.csproj"
COPY . .
WORKDIR "/src/OctopusSamples.OctoPetShop.Web"
RUN dotnet build "OctopusSamples.OctoPetShop.Web.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "OctopusSamples.OctoPetShop.Web.csproj" -c Release -o /app/publish

ENV ASPNETCORE_URLS="http://+:5000;https://+:5001"
ENV ASPNETCORE_ENVIRONMENT="Production"
RUN ["dotnet", "dev-certs", "https"]

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "OctopusSamples.OctoPetShop.Web.dll"]