#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/runtime:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["OctopusSamples.OctoPetShop.Database/OctopusSamples.OctoPetShop.Database.csproj", "OctopusSamples.OctoPetShop.Database/"]
RUN dotnet restore "OctopusSamples.OctoPetShop.Database/OctopusSamples.OctoPetShop.Database.csproj"
COPY . .
WORKDIR "/src/OctopusSamples.OctoPetShop.Database"
RUN dotnet build "OctopusSamples.OctoPetShop.Database.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "OctopusSamples.OctoPetShop.Database.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "OctopusSamples.OctoPetShop.Database.dll"]