name: CI - Containers

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:
    
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    
    outputs:
      version: ${{ steps.version-generator.outputs.version }}
      
    steps:
    
     - uses: actions/checkout@v3
    
     - name: Login to DockerHub
       uses: docker/login-action@v2
       with:
        username: ${{ secrets.DOCKERHUB_SAMPLES_USERNAME }}
        password: ${{ secrets.DOCKERHUB_SAMPLES_PASSWORD }}
        
     - name: Set Version Number

       id: version-generator
       run: echo "version=$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER" >> $GITHUB_OUTPUT

     - name: Build OctoPetShop web container
       run: |
        docker build ./OctopusSamples.OctoPetShop.Web --file ./OctopusSamples.OctoPetShop.Web/dockerfile --tag octopussamples/octopetshop-web-enterprise:${{ steps.version-generator.outputs.version }}
        docker push octopussamples/octopetshop-web:${{ steps.version-generator.outputs.version }}
        
     - name: Build OctoPetShop product service container
       run: | 
        docker build ./OctopusSamples.OctoPetShop.ProductService --file ./OctopusSamples.OctoPetShop.ProductService/dockerfile --tag octopussamples/octopetshop-productservice-enterprise:${{ steps.version-generator.outputs.version }}
        docker push octopussamples/octopetshop-productservice:${{ steps.version-generator.outputs.version }}
        
     - name: Build OctoPetShop shopping cart container
       run: | 
        docker build ./OctopusSamples.OctoPetShop.ShoppingCartService --file ./OctopusSamples.OctoPetShop.ShoppingCartService/dockerfile --tag octopussamples/octopetshop-shoppingcartservice-enterprise:${{ steps.version-generator.outputs.version }}
        docker push octopussamples/octopetshop-shoppingcartservice:${{ steps.version-generator.outputs.version }}
        
     - name: Build OctoPetShop database container
       run: | 
        docker build ./OctopusSamples.OctoPetShop.Database --file ./OctopusSamples.OctoPetShop.Database/dockerfile --tag octopussamples/octopetshop-database-enterprise:${{ steps.version-generator.outputs.version }}
        docker push octopussamples/octopetshop-database:${{ steps.version-generator.outputs.version }}
        
        
  Push-build-information:
       
      name: 🐙Push Build Information
      needs: build 
      runs-on: ubuntu-latest
      
      env:
        OCTOPUS_URL: ${{ secrets.OCTOPUS_DEMO_URL }}
        OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_DEMO_API_KEY }}
        OCTOPUS_SPACE: ${{ secrets.OCTOPUS_DEMO_SPACE }}
      

      steps:
      - uses: OctopusDeploy/push-build-information-action@v3
        name: Push Build Information
        with:
          version: ${{ needs.build.outputs.version }}
          packages: |
            octopussamples/octopetshop-web
            octopussamples/octopetshop-productservice
            octopussamples/octopetshop-shoppingcartservice
            octopussamples/octopetshop-database
          
