name: .NET Core 

on:
  workflow_dispatch:
  push:
    branches: 'master'

permissions:
  id-token: write

#env:
#  OCTOPUS_SPACE: Akira Yamamoto

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version-generator.outputs.version }}

    steps:
    - uses: actions/checkout@v2

    - name: Login to Octopus Deploy 
      uses: OctopusDeploy/login@v1
      with: 
        server: https://demo.octopus.app
        service_account_id: 4d50c8ac-1515-4351-96a7-4a82d55d55ff

    - name: Set Version Number
      id: version-generator
      run: echo "version=$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER" >> $GITHUB_OUTPUT

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Create artifacts folder
      run: |
        mkdir "$GITHUB_WORKSPACE/artifacts"
        mkdir "$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoPetShop.Database"
        mkdir "$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoPetShop.Web"
        mkdir "$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoPetShop.ProductService"
        mkdir "$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoPetShop.ShoppingCartService"

    - name: Publish OctoPetShopDatabase
      run: dotnet publish OctopusSamples.OctoPetShop.Database/OctopusSamples.OctoPetShop.Database.csproj --configuration Release --no-restore --output "$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoPetShop.Database"

    - name: Publish OctoPetShopWeb
      run: dotnet publish OctopusSamples.OctoPetShop.Web/OctopusSamples.OctoPetShop.Web.csproj --configuration Release --no-restore --output "$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoPetShop.Web"

    - name: Publish OctoPetShopProductService
      run: dotnet publish OctopusSamples.OctoPetShop.ProductService/OctopusSamples.OctoPetShop.ProductService.csproj --configuration Release --no-restore --output "$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoPetShop.ProductService"

    - name: Publish OctoPetShopShoppingCartService
      run: dotnet publish OctopusSamples.OctoPetShop.ShoppingCartService/OctopusSamples.OctoPetShop.ShoppingCartService.csproj --configuration Release --no-restore --output "$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoPetshop.ShoppingCartService"

    - name: Package OctoPetShop.Database 🐙
      uses: OctopusDeploy/create-nuget-package-action@v4
      with:
        package_id: "OctoPetShop.Database"
        version: "${{ steps.version-generator.outputs.version }}"
        nuspec_description: "OctoPetShop Database project"
        nuspec_authors: "OctopusSamples"
        output_folder: "${{ github.workspace }}/artifacts"
        base_path: "${{ github.workspace }}/artifacts/OctopusSamples.OctoPetShop.Database"
        files: |
          **/*.*

    - name: Package OctoPetShop.Web 🐙
      uses: OctopusDeploy/create-nuget-package-action@v4
      with:
        package_id: "OctoPetShop.Web"
        version: "${{ steps.version-generator.outputs.version }}"
        nuspec_description: "OctoPetShop Web project"
        nuspec_authors: "OctopusSamples"
        output_folder: "${{ github.workspace }}/artifacts"
        base_path: "${{ github.workspace }}/artifacts/OctopusSamples.OctoPetShop.Web"
        files: |
          **/*.*

    - name: Package OctoPetShop.ProductService 🐙
      uses: OctopusDeploy/create-nuget-package-action@v4
      with:
        package_id: "OctoPetShop.ProductService"
        version: "${{ steps.version-generator.outputs.version }}"
        nuspec_description: "OctoPetShop ProductService project"
        nuspec_authors: "OctopusSamples"
        output_folder: "${{ github.workspace }}/artifacts"
        base_path: "${{ github.workspace }}/artifacts/OctopusSamples.OctoPetShop.ProductService"
        files: |
          **/*.*

    - name: Package OctoPetShop.ShoppingCartService 🐙
      uses: OctopusDeploy/create-nuget-package-action@v4
      with:
        package_id: "OctoPetShop.ShoppingCartService"
        version: "${{ steps.version-generator.outputs.version }}"
        nuspec_description: "OctoPetShop ShoppingCartService project"
        nuspec_authors: "OctopusSamples"
        output_folder: "${{ github.workspace }}/artifacts"
        base_path: "${{ github.workspace }}/artifacts/OctopusSamples.OctoPetShop.ShoppingCartService"
        files: |
          **/*.*

    # - name: Publish Artifacts to Octopus
    #   uses: OctopusDeploy/push-package-action@v3
    #   env:
    #     OCTOPUS_SPACE: "Demo Template"
    #   with: 
    #     packages: |
    #       artifacts/OctoPetShop.Database.${{ steps.version-generator.outputs.version }}.zip
    #       artifacts/OctoPetShop.Web.${{ steps.version-generator.outputs.version }}.zip
    #       artifacts/OctoPetShop.ProductService.${{ steps.version-generator.outputs.version }}.zip
    #       artifacts/OctoPetShop.ShoppingCartService.${{ steps.version-generator.outputs.version }}.zip

    - name: Add GitHub NuGet Source
      run: |
        dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
          --name "GitHub" \
          --username "${{ github.actor }}" \
          --password "${{ secrets.GITHUB_TOKEN }}" \
          --store-password-in-clear-text


    - name: Push NuGet packages to GitHub NuGet repository
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    - run: dotnet nuget push "${{ github.workspace }}/artifacts/*.nupkg" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}

    - uses: OctopusDeploy/push-build-information-action@v3
      name: Push Build Information 🐙
      env:
        OCTOPUS_SPACE: "Demo Template"
      with:
        version: ${{ steps.version-generator.outputs.version }}
        packages: |
          OctoPetShop.Database
          OctoPetShop.Web
          OctoPetShop.ProductService
          OctoPetShop.ShoppingCartService

    # - name: Create a release in Octopus Deploy 🐙
    #   id: create-release
    #   uses: OctopusDeploy/create-release-action@v3
    #   with:
    #     project: 'OctoPetShop'
    #     release_number: ${{ steps.version-generator.outputs.version }}

    # - uses: OctopusDeploy/deploy-release-action@v3
    #   id: deploy-release-to-development
    #   name: "Deploy release ${{ steps.version-generator.outputs.version }} to Development 🐙"
    #   with:
    #     project: 'OctoPetShop'
    #     release_number: ${{ steps.version-generator.outputs.version }}
    #     environments: "Development"

    # - uses: OctopusDeploy/await-task-action@v3
    #   id: "wait-for-deploy-development"
    #   name: "Wait for deployment of ${{ steps.version-generator.outputs.version }} to complete 🐙"
    #   with:
    #     server_task_id: ${{ fromJson(steps.deploy-release-to-development.outputs.server_tasks)[0].serverTaskId }}

    # - uses: OctopusDeploy/deploy-release-action@v3
    #   id: deploy-release-to-homologation
    #   name: "Deploy release ${{ steps.version-generator.outputs.version }} to Homologation 🐙"
    #   with:
    #     project: 'OctoPetShop'
    #     release_number: ${{ steps.version-generator.outputs.version }}
    #     environments: "Homologation"

    # - uses: OctopusDeploy/await-task-action@v3
    #   id: "wait-for-deploy-homologation"
    #   name: "Wait for deployment of ${{ steps.version-generator.outputs.version }} to complete 🐙"
    #   with:
    #     server_task_id: ${{ fromJson(steps.deploy-release-to-homologation.outputs.server_tasks)[0].serverTaskId }}

