name: 'Build and Deploy to Octopus Deploy'
#new
on:
  push:
    branches:
      - '"master"'

env:  
  OCTOPUS_PROJECT: GitHub-Actions
  OCTOPUS_SPACE: Spaces-1115
  PACKAGE_NAME: PackageName
  API_KEY: API-ASADASDASDASKDASKL
  OCTOPUS_URL: https://octopus-operations.octopus.app/

jobs:
 build:
   name: Create Release
   runs-on: ubuntu-latest

   steps:
   - name: Create Release
     id: create_release
     uses: OctopusDeploy/create-release-action@fea7e7b45c38c021b6bc5a14bd7eaa2ed5269214 #v3.2.2
     with:
       project: '${{ env.OCTOPUS_PROJECT }}'
       space: '${{ env.OCTOPUS_SPACE }}'
       packages: '*:${{ env.PACKAGE_NAME }}'
       api_key: ${{ env.API_KEY }}
       server: ${{ env.OCTOPUS_URL }}
